### ISSUE TITLE
Updates for katsumi =)

### ISSUE THREAD

**Issue by MarbleCeo** [theogobinet/Katsumi#1]
Please can you provide more updates on katsumi, plus upload some more projects about Blockchain, id like to see more of that, the base of katsumi is very useful and less complex to work. Im building a blockchain + ecosystem would be nice to have some help more freedom is always good in these dark days

**Comment by n3rada** [comment]
Thank you for your interest in our past project!

This project was carried out at the University/Engineering School. Thus, there are no plans to make any updates. In fact, it serves mainly as an example of the implementation of numerous mathematical functions and methods used in cryptography. 🧮

I invite you to read the README.md in more detail or to have a look at the code if you're interested. The code is a bit old, but logically well done (apart from the fact that no OOP was done). 🐍

It's not advisable in terms of security to implement your own cryptographic protocols, but you can use libraries that are designed and maintained for this purpose!
